# Generated by Django 4.0.4 on 2022-05-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'FAQ 카테고리',
                'verbose_name_plural': 'FAQ 카테고리',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_service.faqcategory'),
        ),
    ]
