# Generated by Django 4.0.4 on 2022-05-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_faqcategory_faq_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=1000, null=True, verbose_name='답변'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_service.faqcategory'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, null=True, verbose_name='질문'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='카테고리 제목'),
        ),
    ]
