# Generated by Django 4.0.4 on 2022-05-15 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='청약 날짜'),
        ),
    ]
