# Generated by Django 4.0.4 on 2022-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiry',
            field=models.BooleanField(default=False, verbose_name='만료'),
        ),
    ]
