export { default as Home } from './Home';
export { default as Detail } from './Detail';
export { default as Mypage } from './Mypage';
export { default as Search } from './Search';
export { default as UserModify } from './UserModify';
export { default as Like } from './Like';
export { default as Login } from './Login';
export { default as Help } from './Help';
export { default as NotFound } from './NotFound';
